### ISSUE TITLE
Data For Connections

### ISSUE THREAD

**Issue by BMark1213** [WychWitch/Obsidian-Dice-Roller-Tables#3]
Hello! 

I am new to Obsidian. I have been looking at your tables and they are amazing! I am excited to use them in my upcoming campaign. However, I am having trouble understanding these two lines of code

`dice: #dnd/npc\|link`
`dice: #dnd/factions\|link`

I am not sure if I am supposed to make a new table or if it is supposed to be reading the names of files in a folder. Let me know. 

Thanks again

**Comment by wychwitch** [comment]
OH those are tags for the dice to roll from! You can roll not just over table notes or folders, but even just files tagged with specific tags!

For example, #dnd/npc\|link will pull a random note tagged with #dnd/npc and insert it as a link! without the |\link itll insert the entire page

**Comment by BMark1213** [comment]
Oh ok perfect thank you!! 

Does it have to be /npc\|link

or should it just be /npc|link?

Thanks again for responding. :)

**Comment by wychwitch** [comment]
> Oh ok perfect thank you!!
> 
> Does it have to be /npc|link
> 
> or should it just be /npc|link?
> 
> Thanks again for responding. :)

I'm assuming you meant `npc\|link` vs `npc|link` lmao 

It depends on where you're using it in! In rant, | is a special character so I had to escape it with \\. However if you're using the dice plugin outside of rant, then | is totally fine!

**Comment by BMark1213** [comment]
Ok perfect thanks again :)
